### ISSUE TITLE
Getting a KeyFrameEffect is not defined error

### ISSUE THREAD

**Issue by npezza93** [alchapone/polymer-elements-rails#1]
Seems to be occurring in the opaque-animation component. Only occurs using this gem. Any ideas why this is happening? 

*Edit - This might be caused by an issue in polymer-rails gem with the webcomponents.js file

**Comment by npezza93** [comment]
_FIXED_ When using any neon elements be sure to add the following line to your application.js file:

```
//= require web-animations-js/web-animations-next-lite.min
```

**Comment by builtbyproxy** [comment]
Just a quick bump, for anyone wondering.
This was an AWESOME fix thankyou @npezza93 

run: bower install web-animations/web-animations-js
and then include in your polymer component: 
<link rel="import" href="../../bower_components/web-animations-js/web-animations-next-lite.min.html">

A bit different to the require but yeah, be aware your folder structure could be different depending where your bower components are.

Thanks again @npezza93
