### ISSUE TITLE
Usage is confusing me

### ISSUE THREAD

**Issue by ghost** [alchapone/polymer-elements-rails#4]
you said on the polymer-paper-rails repo that polymer-paper-rails is not a valid gem anymore, but it's still part of the usage.

So what i really need to do?

**Comment by alchaplinsky** [comment]
If you're using polymer v1.0.x, simply remove those gems from your Gemfile and add `polymer-elements-rails` to it.

**Comment by ghost** [comment]
Ok. Thanks man :)
