### ISSUE TITLE
Precompile error on .js.map files

### ISSUE THREAD

**Issue by tddrmllr** [alchapone/polymer-elements-rails#6]
Apparently `.js.map` files are supported in the latest versions of Sprockets, but we're not quite there yet. Getting an error on precompile. Is there a workaround for Rails 3.2?

```
Unexpected token: punc (:) (line: 1, col: 11, pos: 11)

Error
    at new JS_Parse_Error (<eval>:1720:22)
    at js_error (<eval>:1728:15)
    at croak (<eval>:2189:17)
    at token_error (<eval>:2196:17)
    at unexpected (<eval>:2202:17)
    at Object.semicolon (<eval>:2222:51)
    at prog1 (<eval>:2770:29)
    at simple_statement (<eval>:2362:35)
    at <eval>:2257:59
    at block_ (<eval>:2459:32)
  (in /Users/toddmiller/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/bundler/gems/polymer-elements-rails-76e10df1b48c/app/assets/components/web-animations-js/web-animations-next-lite.min.js.map)new JS_Parse_Error ((execjs):1720:22)
js_error ((execjs):1728:15)
croak ((execjs):2189:17)
token_error ((execjs):2196:17)
unexpected ((execjs):2202:17)
Object.semicolon ((execjs):2222:51)
prog1 ((execjs):2770:29)
simple_statement ((execjs):2362:35)
(execjs):2257:59
block_ ((execjs):2459:32)
```

**Comment by 7Ds7** [comment]
I had the same problem and it was only "solved" by dropping that same file

**Comment by rxever** [comment]
@tikitikifoofoo have you overcome this issue and if so how? Thank you for any answers!

**Comment by tddrmllr** [comment]
@rxever I just made my own fork of the branch and deleted those files: https://github.com/tikitikifoofoo/polymer-elements-rails. But now I'm getting this issue: https://github.com/alchapone/polymer-rails/issues/57, which I haven't figured out how to solve yet.

**Comment by rxever** [comment]
Hey @tikitikifoofoo for me your branch is working fine! Your problem might be connected with not having the layouts in their usual folder? As far as I see you have them in a subfolder of layouts folder? app/views/layouts/_backend_assets.html.erb:7. Maybe try putting them out of the _backend _assets folder into layouts folder? The assets.rb should be like: 

```
Rails.application.config.assets.precompile += %w( application.html )
```

Though you mentioned you have it that way.
Plus I think your sprockets version must not be higher than 3.0.

**Comment by alchaplinsky** [comment]
Added those (and others) files to .gitignore. Check out v1.0.1
